/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import com.google.protobuf.Message;
import dao.CTDHDAO;
import dao.DoanhThuDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.NhanVienDAO;
import dao.SanPhamDAO;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.CTHD;
import model.HoaDon;
import model.NhanVien;

/**
 *
 * @author ACER
 */
public class MuaHangFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserBuy
     */
    public MuaHangFrame() {
        initComponents();
        init();
    }
    int xx,yy;
    SanPhamDAO spDAO=new SanPhamDAO();
    HoaDonDAO dhDAO=new HoaDonDAO();
    KhachHangDAO khDAO=new KhachHangDAO();
    NhanVienDAO nvDAO=new NhanVienDAO();
    CTDHDAO ctDAO=new CTDHDAO();
    DoanhThuDAO dtDAO=new DoanhThuDAO();
    String danhmuc[];
    String nhacungcap[];
    private int soluong=0;
    private double gia=0;
    private double tong=0;
    private int idDonHang=0;
    private String tenkhachhang;
    private double tinhtien=0;
    private int stt=1;
    private int flagDiem = 0;
    
    int r;
    DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void init(){
    
        jTextFieldIDDonHang.setText(String.valueOf(dhDAO.khoiTaoID()));
       // idDonHang = dhDAO.khoiTaoID();
  
        
        danhmuc=new String[spDAO.soLuongDanhMuc()];
        danhmuc=spDAO.danhMuc();
        for(String dm:danhmuc){
        
            this.jComboBox1.addItem(dm);
        }
        
        nhacungcap=new String[spDAO.soLuongNhaCungCap()];
        nhacungcap=spDAO.nhaCungCap();
        for(String ncc:nhacungcap){
        
            this.jComboBox1.addItem(ncc);
        }
        spDAO.loadData(jTableSanPham);
    
       // jTextFieldTenKhachHang.setText(khDAO.getTen(Integer.valueOf(jTextFieldSDT.getText())));
    }
    private void clear() {

        jTextFieldTen.setText("");
        jTextFieldSoLuong.setText("");
        
  
        jTableSanPham.clearSelection();
        jTableDonHang.clearSelection();
        this.spDAO.loadData(this.jTableSanPham);
        

    }
    private void refresh() {
        jTextFieldTen.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldTenKhachHang.setText("");
        jTextFieldThanhTien.setText("");
        jTextField2.setText("");
        jTextFieldSDT.setText("");
        jDateChooserNgayMua.setCalendar(null);
        tinhtien = 0;
        stt = 0;
        
        jTableSanPham.clearSelection();
        DefaultTableModel md = (DefaultTableModel) jTableDonHang.getModel();
        md.setNumRows(0);
        
        this.spDAO.loadData(this.jTableSanPham);
    }
    private void tableSanPham(){
    
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTen = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldThanhTien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTaiTrang = new javax.swing.JLabel();
        jDateChooserNgayMua = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextFieldIDDonHang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextFieldTenKhachHang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton6.setText("Tìm kiếm");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 110, 30));

        jTableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Giá", "Số lượng", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDonHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTableDonHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 710, 400));

        jTableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Sản phẩm", "Tên sản phẩm", "Danh mục", "Nhà cung cấp", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSanPham);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 690, 400));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 180, -1));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Sản phẩm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("Đơn hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, -1, -1));

        jTextFieldTen.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen.setEditable(false);
        jTextFieldTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenActionPerformed(evt);
            }
        });
        jTextFieldTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTenKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 300, -1));

        jTextFieldSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSoLuongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 300, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ID Hóa đơn");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, -1, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("In hóa đơn");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 600, 110, 40));

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton4.setText("Thêm");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 110, 40));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 550, 110, 40));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton3.setText("Xác nhận");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 600, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 255));
        jLabel6.setText("Thành tiền");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 550, 120, 40));

        jTextFieldThanhTien.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldThanhTien.setEditable(false);
        jTextFieldThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldThanhTienActionPerformed(evt);
            }
        });
        jTextFieldThanhTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldThanhTienKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 600, 140, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 1270, -1));

        jLabelTaiTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTaiTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        jLabelTaiTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTaiTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseExited(evt);
            }
        });
        jPanel1.add(jLabelTaiTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jDateChooserNgayMua.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooserNgayMua, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Ngày mua");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 220, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 255));
        jLabel8.setText("Danh mục:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 270, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton5.setText("Tìm kiếm tên sản phẩm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jTextFieldIDDonHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDDonHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldIDDonHang.setEditable(false);
        jTextFieldIDDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIDDonHangMouseClicked(evt);
            }
        });
        jTextFieldIDDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDDonHangActionPerformed(evt);
            }
        });
        jTextFieldIDDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDDonHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 300, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Tên sản phẩm");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, 20));

        jTextFieldSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSDTActionPerformed(evt);
            }
        });
        jTextFieldSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSDTKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Điểm thưởng tích lũy");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Số điện thoại");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 90, 20));

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton7.setText("Sử dụng điểm tích lũy");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 650, 230, 40));

        jTextFieldTenKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTenKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTenKhachHang.setEditable(false);
        jTextFieldTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenKhachHangActionPerformed(evt);
            }
        });
        jTextFieldTenKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTenKhachHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 180, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Tên khách hàng");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pink_gradient.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 700));
        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextFieldTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int select=jTableDonHang.getSelectedRow();
        if(select==-1){
        
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
            double Gia = Double.parseDouble(jTableDonHang.getValueAt(select, 4).toString());
            tong = Gia;
            tinhtien-=tong;
            jTextFieldThanhTien.setText(String.format(Locale.US,"%.2f",tinhtien));
             model=(DefaultTableModel) jTableDonHang.getModel();
             model.removeRow(select);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldThanhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldThanhTienActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabelTaiTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseClicked
        refresh();
        
        flagDiem=0;
    }//GEN-LAST:event_jLabelTaiTrangMouseClicked

    private void jLabelTaiTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseEntered
        jLabelTaiTrang.setText("Tải lại trang");
    }//GEN-LAST:event_jLabelTaiTrangMouseEntered

    private void jLabelTaiTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseExited
        jLabelTaiTrang.setText("");
    }//GEN-LAST:event_jLabelTaiTrangMouseExited

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        model = (DefaultTableModel) jTableSanPham.getModel();
        r = jTableSanPham.getSelectedRow();
        

       
        jTextFieldTen.setText(model.getValueAt(r, 1).toString());

        soluong = Integer.parseInt(model.getValueAt(r, 5).toString());
        gia = Double.parseDouble(model.getValueAt(r, 4).toString());
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void jTextFieldSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSoLuongKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSoLuongKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i=1;
        if (jTextFieldSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập số lượng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (jDateChooserNgayMua.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Chọn ngày mua !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
         else if (jTextFieldTenKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập tên khách hàng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
          else if (jTextFieldSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
        else {

            if (!(soluong <= 0)) {
                int soluongnhap = Integer.parseInt(jTextFieldSoLuong.getText());
                if (soluongnhap != 0) {
                    if(!(soluongnhap>soluong)){
                
                 
                    String tensanpham=jTextFieldTen.getText();
                    String tong=String.format(Locale.US,"%.2f", gia*(double)soluongnhap);
                    Object[] row={stt,tensanpham,gia,soluongnhap,tong};
                    model=(DefaultTableModel) jTableDonHang.getModel();
                    model.addRow(row);
                    tinhtien+=gia*(double)soluongnhap;
                    jTextFieldThanhTien.setText(String.format(Locale.US,"%.2f",tinhtien));
                    
                    jTextFieldTen.setText("");
                    jTextFieldSoLuong.setText("");
                    clear();
                    stt++;
                }
                    else{
                        JOptionPane.showMessageDialog(this, "Không đủ sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Nhập số lượng lớn hơn 0 !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } 
            else if(jDateChooserNgayMua.getDate()==null) {
                JOptionPane.showMessageDialog(this, "Chọn ngày mua !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Sản phẩm đã hết !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        model = (DefaultTableModel) jTableDonHang.getModel();
        String email = GiaoDienNguoiDungFrame.jLabelEmail.getText().toString();
        if (jDateChooserNgayMua.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Chọn ngày mua !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        if (jTextFieldSDT == null) {
            JOptionPane.showMessageDialog(this, "Chọn số điện thoại !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        if (model.getRowCount() > 0) {

            int id_donhang = Integer.parseInt(jTextFieldIDDonHang.getText());
            String tenKH = jTextFieldTenKhachHang.getText();
            String sdt = jTextFieldSDT.getText();
            double gia = Double.valueOf(jTextFieldThanhTien.getText());
            java.util.Date utilNgayMua = jDateChooserNgayMua.getDate();
            java.sql.Date ngaymua = new java.sql.Date(utilNgayMua.getTime());
            int id_nv=nvDAO.getId(email);
            int id_kh=khDAO.getId(sdt);
            HoaDon hd = new HoaDon(id_donhang, tenKH, sdt, gia, ngaymua, id_nv, id_kh);
            dhDAO.insert(hd, email);
            for (int i = 0; i < model.getRowCount(); i++) {

                int stt = Integer.parseInt(model.getValueAt(i, 0).toString());
                String tensp = model.getValueAt(i, 1).toString();
                double giatien = Double.parseDouble(model.getValueAt(i, 2).toString());
                int sl = Integer.parseInt(model.getValueAt(i, 3).toString());
                double tong = Double.parseDouble(model.getValueAt(i, 4).toString());
                int id_sp = spDAO.getID(tensp);

                CTHD ct = new CTHD(id_donhang, stt, tensp, id_sp, sl, tong);
                ctDAO.insert(ct);
                int SLmoi = dhDAO.getSLSP(tensp) - sl;
                dhDAO.updateSanPham(tensp, SLmoi);
            }
            if(flagDiem == 1)
            {
                khDAO.updateDiem(id_kh, 0);
            }
            double tichdiem = Double.valueOf(jTextFieldThanhTien.getText()) / 1000.0;
            double diemmoi = khDAO.getDiem(id_kh) + tichdiem;
            khDAO.updateDiem(id_kh, diemmoi);

            //java.util.Date utilNgayMua = jDateChooserNgayMua.getDate();
            java.util.Calendar calendar = java.util.Calendar.getInstance();
            calendar.setTime(utilNgayMua);
            int month = calendar.get(java.util.Calendar.MONTH)+1;
            
            double doanhthuhientai = Double.valueOf(jTextFieldThanhTien.getText());
            double doanhthumoi=dtDAO.getDoanhThu(id_nv, month)+doanhthuhientai;
            dtDAO.updateDoanhThu(id_nv, month, doanhthumoi);
            
            

            JOptionPane.showMessageDialog(this, "Mua hàng thành công !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            init();
            refresh();
        } else {

            JOptionPane.showMessageDialog(this, "Giỏ hàng trống !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tenkhachhang=khDAO.getTen(GiaoDienNguoiDungFrame.jLabelEmail.getText());
            MessageFormat mf = new MessageFormat("Khách hàng : "+jTextFieldTenKhachHang.getText()+ " "+" "+ "Tổng tiền : " + tinhtien);
            MessageFormat mf2 = new MessageFormat("Page{0, number,integer}");
            jTableDonHang.print(JTable.PrintMode.FIT_WIDTH, mf, mf2);
          
        } catch (PrinterException e) {
            Logger.getLogger(HoaDonDAO.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.jTextField1.getText().equals("")) JOptionPane.showMessageDialog(this, "Mục tìm kiếm rỗng!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        else this.spDAO.searchForName(this.jTableSanPham,this.jTextField1.getText());                                        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(this.jComboBox1.getSelectedItem().toString().equals("Tất cả")) this.spDAO.loadData(this.jTableSanPham);
        else this.spDAO.loadDataByItem(this.jTableSanPham,this.jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTenKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldTenKeyTyped

    private void jTextFieldThanhTienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldThanhTienKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldThanhTienKeyTyped

    private void jTextFieldIDDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDDonHangActionPerformed
        
    }//GEN-LAST:event_jTextFieldIDDonHangActionPerformed

    private void jTextFieldIDDonHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDonHangKeyTyped
       
    }//GEN-LAST:event_jTextFieldIDDonHangKeyTyped

    private void jTextFieldSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTActionPerformed

    private void jTextFieldSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSDTKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTKeyTyped

    private void jTextFieldTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenKhachHangActionPerformed

    private void jTextFieldTenKhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTenKhachHangKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenKhachHangKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextFieldTenKhachHang.setText(khDAO.getTen(jTextFieldSDT.getText()));
        this.jTextField2.setText(khDAO.getDiemBySDT(jTextFieldSDT.getText()));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        double diem = Double.parseDouble(this.jTextField2.getText());
        
        tinhtien = tinhtien - diem*10;
        jTextFieldThanhTien.setText(String.format(Locale.US,"%.2f",tinhtien));
        this.jTextField2.setText("0");
        
        flagDiem = 1;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldIDDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIDDonHangMouseClicked
        
    }//GEN-LAST:event_jTextFieldIDDonHangMouseClicked
    
   // private boolean  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaHangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTaiTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDonHang;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldIDDonHang;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldTenKhachHang;
    private javax.swing.JTextField jTextFieldThanhTien;
    // End of variables declaration//GEN-END:variables
}
