/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.CTDHDAO;
import dao.HoaDonDAO;
import dao.SanPhamDAO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class QuanLyDonHangFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChonNhaCungCapFrame
     */
    DefaultTableModel model = new DefaultTableModel();
    public QuanLyDonHangFrame() {
        initComponents();
        init();
    }
    String nhacungcap[];
    int xx,yy;
    SanPhamDAO spDAO=new SanPhamDAO();
    HoaDonDAO dhDAO=new HoaDonDAO();
    CTDHDAO cthdDAO=new CTDHDAO();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDH = new javax.swing.JTable();
        jTextFieldIDKH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIDDonHang = new javax.swing.JTextField();
        jTextFieldSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldGiaTong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTong = new javax.swing.JTextField();
        jTextFieldTenKH = new javax.swing.JTextField();
        jTextFieldSL = new javax.swing.JTextField();
        jTextFieldNgayMua = new javax.swing.JTextField();
        jTextFieldNhanVien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIDNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelTaiTrang = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCTHD = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Đơn hàng", "ID Khách hàng", "Tên khách hàng", "ID Nhân viên", "Tên nhân viên", "Tổng", "Ngày mua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDH);
        if (jTableDH.getColumnModel().getColumnCount() > 0) {
            jTableDH.getColumnModel().getColumn(0).setHeaderValue("ID Đơn hàng");
            jTableDH.getColumnModel().getColumn(6).setHeaderValue("Ngày mua");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 710, 430));

        jTextFieldIDKH.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDKH.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldIDKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKHKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 130, -1));

        jLabel12.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, 40, -1));

        jTextFieldIDDonHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDDonHang.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldIDDonHang.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldIDDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDDonHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 130, -1));

        jTextFieldSanPham.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSanPham.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSanPhamKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 160, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 100, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Khách hàng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID Đơn hàng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 100, -1));

        jTextFieldGiaTong.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldGiaTong.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldGiaTong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGiaTongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldGiaTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 560, 160, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Ngày mua");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 100, -1));

        jTextFieldTong.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTong.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldTong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 150, -1));

        jTextFieldTenKH.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTenKH.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTenKHKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 140, -1));

        jTextFieldSL.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSL.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSLKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 160, -1));

        jTextFieldNgayMua.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNgayMua.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldNgayMua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNgayMuaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNgayMua, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, 160, -1));

        jTextFieldNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNhanVienKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 150, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tên nhân viên");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 100, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ID Khách hàng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tổng");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 100, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Số lượng");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 537, 100, 20));

        jTextFieldIDNV.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDNV.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldIDNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDNVKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 140, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("ID Nhân viên");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 120, -1));

        jLabelTaiTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTaiTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        jLabelTaiTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTaiTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseExited(evt);
            }
        });
        jPanel1.add(jLabelTaiTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Giá tổng");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 540, 100, 20));

        jTableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID Sản phẩm", "Sản phẩm", "Số lượng", "Giá tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCTHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCTHD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 710, 430));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("Chi tiết hóa đơn");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 200, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("Đơn hàng");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xem CTHD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anh-nen-lam-slide_023656040.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1510, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init(){
    
       
        dhDAO.loadData(jTableDH);

    }

    public void loadEmptyTable(JTable table) {

        model = new DefaultTableModel();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }

    private void clear() {
        jTextFieldIDDonHang.setText("");
        jTextFieldSanPham.setText("");
        jTextFieldIDKH.setText("");
        jTextFieldTenKH.setText("");
  
        jTextFieldGiaTong.setText("");
        jTextFieldTong.setText("");
        jTextFieldSL.setText("");
        jTextFieldGiaTong.setText("");
        jTextFieldIDNV.setText("");
        jTextFieldNhanVien.setText("");
        jTextFieldNgayMua.setText("");
        
        DefaultTableModel model=(DefaultTableModel) jTableCTHD.getModel();
        model.setRowCount(0);
        
        this.dhDAO.loadData(jTableDH);
        
    }
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTableDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDHMouseClicked
        model = (DefaultTableModel) jTableDH.getModel();
        int r = jTableDH.getSelectedRow();
        jTextFieldIDDonHang.setText(model.getValueAt(r, 0).toString());
     
        jTextFieldIDKH.setText(model.getValueAt(r, 1).toString());
        jTextFieldTenKH.setText(model.getValueAt(r, 2).toString());
         jTextFieldIDNV.setText(model.getValueAt(r, 3).toString());
        jTextFieldNhanVien.setText(model.getValueAt(r, 4).toString());
        jTextFieldTong.setText(model.getValueAt(r, 5).toString());
        jTextFieldNgayMua.setText(model.getValueAt(r, 6).toString());
        
    }//GEN-LAST:event_jTableDHMouseClicked

    private void jLabelTaiTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseClicked
        clear();
    }//GEN-LAST:event_jLabelTaiTrangMouseClicked

    private void jLabelTaiTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseEntered
        jLabelTaiTrang.setText("Tải lại trang");
    }//GEN-LAST:event_jLabelTaiTrangMouseEntered

    private void jLabelTaiTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseExited
        jLabelTaiTrang.setText("");
    }//GEN-LAST:event_jLabelTaiTrangMouseExited

    private void jTextFieldIDDonHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDonHangKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldIDDonHangKeyTyped

    private void jTextFieldIDKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKHKeyTyped
       evt.consume();
    }//GEN-LAST:event_jTextFieldIDKHKeyTyped

    private void jTextFieldTenKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTenKHKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldTenKHKeyTyped

    private void jTextFieldIDNVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDNVKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldIDNVKeyTyped

    private void jTextFieldNhanVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNhanVienKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldNhanVienKeyTyped

    private void jTextFieldTongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTongKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldTongKeyTyped

    private void jTextFieldSLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSLKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldSLKeyTyped

    private void jTextFieldGiaTongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGiaTongKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldGiaTongKeyTyped

    private void jTextFieldNgayMuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNgayMuaKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldNgayMuaKeyTyped

    private void jTableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCTHDMouseClicked
         model = (DefaultTableModel) jTableDH.getModel();
        int r = jTableDH.getSelectedRow();
        jTextFieldSanPham.setText(model.getValueAt(r, 0).toString());
     
        jTextFieldSL.setText(model.getValueAt(r, 1).toString());
        jTextFieldGiaTong.setText(model.getValueAt(r, 2).toString());
    }//GEN-LAST:event_jTableCTHDMouseClicked

    private void jTextFieldSanPhamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSanPhamKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldSanPhamKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(jTextFieldIDDonHang.getText().isEmpty()){       
             JOptionPane.showMessageDialog(this, "Chọn đơn hàng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
       }
       else{
        int id=Integer.valueOf(jTextFieldIDDonHang.getText());
        cthdDAO.loadData(jTableCTHD, id);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDonHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDonHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDonHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDonHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDonHangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTaiTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCTHD;
    private javax.swing.JTable jTableDH;
    private javax.swing.JTextField jTextFieldGiaTong;
    private javax.swing.JTextField jTextFieldIDDonHang;
    private javax.swing.JTextField jTextFieldIDKH;
    private javax.swing.JTextField jTextFieldIDNV;
    private javax.swing.JTextField jTextFieldNgayMua;
    private javax.swing.JTextField jTextFieldNhanVien;
    private javax.swing.JTextField jTextFieldSL;
    private javax.swing.JTextField jTextFieldSanPham;
    private javax.swing.JTextField jTextFieldTenKH;
    private javax.swing.JTextField jTextFieldTong;
    // End of variables declaration//GEN-END:variables
}
