/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.DanhMucDAO;
import dao.NhaCungCapDAO;
import dao.SanPhamDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhaCungCap;
import model.SanPham;

/**
 *
 * @author ACER
 */
public class QuanLySanPhamFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySanPhamFrame
     */
    int xx,yy;
    String danhmuc[];
    String nhacungcap[];
    SanPhamDAO spDAO=new SanPhamDAO();
    DefaultTableModel model=new DefaultTableModel();
    DanhMucDAO dmDAO=new DanhMucDAO();
    NhaCungCapDAO nccDAO=new NhaCungCapDAO();
    
    public QuanLySanPhamFrame() {
        initComponents();
        init();
        spDAO.loadData(jTableSanPham);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void clear() {
        jTextFieldID.setText(String.valueOf(spDAO.khoiTaoID()));
        jTextFieldTen.setText("");
        jTextFieldSoLuong.setText("");
        jTextFieldGia.setText("");
  
        jTableSanPham.clearSelection();
        jTextFieldTimKiem.setText("");
        this.spDAO.loadData(jTableSanPham);

    }
    private  boolean kiemTraKhongRong(){
    
        if(jTextFieldTen.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập tên sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jComboBoxDanhMuc.getSelectedItem()==null){
        
            JOptionPane.showMessageDialog(this, "Chọn danh mục !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
            
        }
        if(jComboBoxNhaCungCap.getSelectedItem()==null){
        
            JOptionPane.showMessageDialog(this, "Chọn danh mục !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        
        }if(jTextFieldSoLuong.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập số lượng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jTextFieldGia.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập giá !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
       
        
        return true;
    }
    private boolean kiemTraSoLuong(String s){
    
        try {
            int a=Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,""+ e+"Điền giá trị là số !!!");
        }
        return false;
    }
    private boolean kiemTraGia(String s){
    
        try {
            double a=Double.parseDouble(s);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,""+ e+"Điền giá trị là số !!!");
        }
        return false;
    }
    private void init(){
    
        danhmuc=new String[spDAO.soLuongDanhMuc()];
        danhmuc=spDAO.danhMuc();
        for(String dm:danhmuc){
        
            jComboBoxDanhMuc.addItem(dm);
        }
        
        nhacungcap=new String[spDAO.soLuongNhaCungCap()];
        nhacungcap=spDAO.nhaCungCap();
        for(String ncc:nhacungcap){
        
            jComboBoxNhaCungCap.addItem(ncc);
        }
        jTextFieldID.setText(String.valueOf(spDAO.khoiTaoID()));
//       
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldTen = new javax.swing.JTextField();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jTextFieldGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDanhMuc = new javax.swing.JComboBox<>();
        jLabelTaiTrang = new javax.swing.JLabel();
        jComboBoxNhaCungCap = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel1.setText("__________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 1200, -1));

        jTableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Danh mục", "Nhà cung cấp", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSanPham);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 1180, 290));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Sản phẩm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 120, -1));

        jTextFieldID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldID.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 350, -1));

        jTextFieldTen.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(jTextFieldTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 350, -1));

        jTextFieldTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 340, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Nhà cung cấp");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 100, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Tên sản phẩm");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm tên sản phẩm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 340, 30));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Lưu");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 100, 30));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cập nhật");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 110, 30));

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Xóa");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 100, 30));

        jTextFieldSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSoLuongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 340, -1));

        jTextFieldGia.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGiaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 340, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setText("Loại danh mục");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setText("Số lượng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("Giá");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        jComboBoxDanhMuc.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jComboBoxDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDanhMucActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 350, -1));

        jLabelTaiTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTaiTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        jLabelTaiTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTaiTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseExited(evt);
            }
        });
        jPanel1.add(jLabelTaiTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jComboBoxNhaCungCap.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(jComboBoxNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 340, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("ID ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/anh-nen-lam-slide_023656040.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jTextFieldTimKiem.getText().equals("")) JOptionPane.showMessageDialog(this, "Mục tìm kiếm rỗng!!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        else this.spDAO.searchForName(this.jTableSanPham,this.jTextFieldTimKiem.getText()); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        
        xx=evt.getX();
        yy=evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabelTaiTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseClicked
        clear();
    }//GEN-LAST:event_jLabelTaiTrangMouseClicked

    private void jLabelTaiTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseEntered
        jLabelTaiTrang.setText("Tải lại trang");
    }//GEN-LAST:event_jLabelTaiTrangMouseEntered

    private void jLabelTaiTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseExited
        jLabelTaiTrang.setText("");
    }//GEN-LAST:event_jLabelTaiTrangMouseExited

    private void jTextFieldSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSoLuongKeyTyped
        
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSoLuongKeyTyped

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        model = (DefaultTableModel) jTableSanPham.getModel();
        int r = jTableSanPham.getSelectedRow();
        jTextFieldID.setText(model.getValueAt(r, 0).toString());
        jTextFieldTen.setText(model.getValueAt(r, 1).toString());
        jComboBoxDanhMuc.setSelectedItem(model.getValueAt(r, 2).toString());
        jComboBoxNhaCungCap.setSelectedItem(model.getValueAt(r, 3).toString());
        jTextFieldGia.setText(model.getValueAt(r, 4).toString());
        jTextFieldSoLuong.setText(model.getValueAt(r, 5).toString());
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(kiemTraKhongRong()){
        
            int id=Integer.parseInt(jTextFieldID.getText());
            String tensanpham=jTextFieldTen.getText();
            String danhmuc = jComboBoxDanhMuc.getSelectedItem().toString();
            String nhacungcap = jComboBoxNhaCungCap.getSelectedItem().toString();
            int id_dm=dmDAO.getID(jComboBoxDanhMuc.getSelectedItem().toString());
            int id_ncc=nccDAO.getIdTen(jComboBoxNhaCungCap.getSelectedItem().toString());
            
            if (kiemTraGia(jTextFieldGia.getText())) {
                double gia = Double.parseDouble(jTextFieldGia.getText());
                if (kiemTraSoLuong(jTextFieldSoLuong.getText())) {

                    int soluong = Integer.parseInt(jTextFieldSoLuong.getText());
                    if (!spDAO.checkID(id)) {
                        SanPham sp = new SanPham(id, tensanpham, danhmuc, nhacungcap, gia, soluong,id_dm,id_ncc);
                        spDAO.insert(sp);
                        QuanLySanPhamFrame spF = new QuanLySanPhamFrame();
                        spF.setVisible(true);
                        spF.pack();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Mã đã tồn tại", "Thông báo", 2);
                    }
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGiaKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldGiaKeyTyped

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
        
            evt.consume();
        
    }//GEN-LAST:event_jTextFieldIDKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        int id = Integer.parseInt(jTextFieldID.getText());
        String tensanpham = jTextFieldTen.getText();
        String danhmuc = jComboBoxDanhMuc.getSelectedItem().toString();
        String nhacungcap = jComboBoxNhaCungCap.getSelectedItem().toString();
        int id_dm = dmDAO.getID(jComboBoxDanhMuc.getSelectedItem().toString());
        int id_ncc = nccDAO.getId(jComboBoxNhaCungCap.getSelectedItem().toString());
        double gia = Double.parseDouble(jTextFieldGia.getText());
        int soluong = Integer.parseInt(jTextFieldSoLuong.getText());
        SanPham sp = new SanPham(id, tensanpham, danhmuc, nhacungcap, gia, soluong, id_dm, id_ncc);
        int a = JOptionPane.showConfirmDialog(null, " Xác nhận xóa sản phẩm", "Thông báo", JOptionPane.OK_CANCEL_OPTION, 0);
        if (a == JOptionPane.OK_OPTION) {
            spDAO.delete((SanPham) sp);
            JOptionPane.showMessageDialog(null, " Sản phẩm đã được xóa");
            QuanLySanPhamFrame ql = new QuanLySanPhamFrame();
            ql.setVisible(true);
            ql.pack();

            this.dispose();

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (kiemTraKhongRong()) {

            int id = Integer.parseInt(jTextFieldID.getText());
            String tensanpham = jTextFieldTen.getText();
            String danhmuc = jComboBoxDanhMuc.getSelectedItem().toString();
            String nhacungcap = jComboBoxNhaCungCap.getSelectedItem().toString();
            int id_dm = dmDAO.getID(jComboBoxDanhMuc.getSelectedItem().toString());
            int id_ncc = nccDAO.getId(jComboBoxNhaCungCap.getSelectedItem().toString());
            if (kiemTraGia(jTextFieldGia.getText())) {
                double gia = Double.parseDouble(jTextFieldGia.getText());
                if (kiemTraSoLuong(jTextFieldSoLuong.getText())) {
                    int soluong = Integer.parseInt(jTextFieldSoLuong.getText());
                    SanPham sp = new SanPham(id, tensanpham, danhmuc, nhacungcap, gia, soluong, id_dm, id_ncc);
                    if (!spDAO.kiemTraIDKhongDuocThayDoi(sp)) {
                        spDAO.update(sp);
                        QuanLySanPhamFrame spF = new QuanLySanPhamFrame();
                        spF.setVisible(true);
                        spF.pack();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Không được thay đổi id", "Thông báo", 2);
                    }
                }

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDanhMucActionPerformed

    private void jTextFieldTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySanPhamFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxDanhMuc;
    private javax.swing.JComboBox<String> jComboBoxNhaCungCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTaiTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTextField jTextFieldGia;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
